title: "YouTube Podcast Analysis"
subtitle: "A Multimodal Study of Audio, Visual, and Engagement Dynamics"
description: >- # this means to ignore newlines until "baseurl:"
  This project analyzes the evolution and performance of podcast content on **YouTube**, combining **audio signal processing**, **natural language processing**, **computer vision**, and **statistical modeling**.

github_repo:
  name: "YouTube Podcast Data Hub "
  url: "https://fiorellov.github.io"
  baseurl: "/YouTubePodcastDataHub"


navbar:
  style :  dual #non modificare
  brand: # Ã¨ il titolo del sito e funziona da bottone (tipicamente per la homepage).
    title :  "US Podcast Big Data Analysis"
    img: "assets/images/Logo_masthead.png"
    url: /
  nav:
    - title: Introduzione 
      url: /#introduzione
    #- title: Topic Modelling
    #  url: /jekyll-ssg
    - title: Topic Extraction
      url: /#topic-extraction
    - title: Sentiment Analysis
      url: /#sentimenti-analysis
    - title: Audio
      url: /#audio
    - title: Frame color
      url: /#frame-color
    - title: Conclusioni 
      url: /#conclusioni



    
    #- title: Audio #Label
      #child:
        #- title: markdown cheatsheet #Label
        #  url: /markdown  #url
        #- title: kramdown cheatsheet #Label
        #  url: /kramdown #url
    #- title: Colori
      #child:
      #  - title: Demo
      #    url: /single
      #  - title: "Sezione 1" #Label
      #    url: /single#sezione-1 #url
      #  - title: "Sezione 1.1" #Label
      #    url: /single#sezione-11 #url
      #  - title: "Sezione 1.2" #Label
      #    url: /single#sezione-12 #url
      #  - title: "Gallerie" #Label
      #    url: /single#galleria #url
      #  - title: "Mappa delle stragi" #Label
      #    url: /single#mappa-delle-stragi #url



googlefonts:
  - url: "https://fonts.googleapis.com/css2?family=Comic+Neue:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap"
  - url: "https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap"
  - url: "https://fonts.googleapis.com/css2?family=Lekton:ital,wght@0,400;0,700;1,400&display=swap"

chulapa-skin:
  skin:  graymor #"gitdev" #"universal" #"graymor" #"graymor" "gitdev-dark" "gitdev"  "academia" "gitdev" "towards" "pear" "twitter-lights-out" "twitter-dim" "wandoo" "lymcha" "twitter" "chulapa" "sunset" "sunset" "minty" "lux" "journal" "deeply"
  vars:
    body-bg: "#181818"
    # font-family-base: "Comic Neue"
    # headings-font-family: "Lekton"


#chulapa-skin:
#  autothemer  :  true
#  vars:
#    primary: "darkorange"



##################################################
#    NON modificare la sezione sottostante
##################################################

# Build settings
theme: chulapa-jekyll
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path

footer:
  links:
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: https://www.linkedin.com/in/fiorello-viteritti/


sass:
  quiet_deps: true

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea/

include:
  - .nojekyll
livereload: true

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
#github_username:  jekyll

future: true
